version: "2"

formatters:
  enable:
    - gci
    - gofumpt

linters:
  default: all
  disable:
    - depguard
    - dupl
    - exhaustive
    - exhaustruct
    - lll
    - mnd
    - paralleltest
    - prealloc
    - rowserrcheck # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - testpackage
    - varnamelen

  settings:
    gocyclo:
      min-complexity: 25
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: true
    tagliatelle:
      case:
        rules:
          json: snake

  exclusions:
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - cyclop
          - funlen
          - gochecknoglobals
        path: (.*)_test.go
